// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kligcyjehzjyaogusvzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsaWdjeWplaHpqeWFvZ3VzdnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NDI5NDcsImV4cCI6MjA5MDExODk0N30.QScR9AjZxq6G3o0_u7u6D4Uulw9gy_I1FTtzhrrG46I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});